### PR TITLE
feat: new issue view support

### PR DESCRIPTION
**Pull request by graypegg**
[With Atlassian sunsetting the old issue view on March 31st](https://support.atlassian.com/jira-core-cloud/docs/manage-the-transition-to-the-new-issue-view/), and me being stubborn, I've tweaked the selectors a bit to work with the new issue view. 

## Changes
* Selectors are now for the new issue page as it appears on Cloud JIRA circa march 2021
* [TurndownJS](https://github.com/domchristie/turndown) added to format the ticket summary in markdown. Won't be interpreted by OmniFocus, but it is more readable.

Capture d’écran, le 2021-03-17 à 11 32 44

### CODE REVIEW

**Comment by prometheas** [comment]
OMG - an actual PR for this! I will review ASAP (will aim for tonight, but have a work deadline… definitely in the days ahead, though). Thank you kindly for this contribution, @graypegg 🙏🏼

**Comment by graypegg** [comment]
No worries and no rush! :) It's honestly quite fragile, the new issue view is pretty different under the hood. But this is just so I could keep writing standup notes after this month haha

**Comment by prometheas** [comment]
> I'll need to circle back and tweak this, done on a lunch break haha

🤣 you're an absolute fucking rock star. There are a handful of people out there (not least of which myself) who'll be quite grateful to you. Will definitely give you props in the release notes on the Play Store, too — LMK if you'd like me to mention you with your Github username or otherwise.

**Comment by graypegg** [comment]
Thought I most post a bump for this!

**Comment by graypegg** [comment]
Notification bump!

**Comment by graypegg** [comment]
Bump!

**Comment by prometheas** [comment]
Also, @graypegg -- thank you for your persistent, kindly-delivered reminders.

**Comment by graypegg** [comment]
No worries at all @prometheas!! I totally get it!! Thanks so much, just useful to have this merged rather than moving around an unpacked extension all the time haha

**Pull request merged**
